#!/bin/bash

# Install DHCP server
apt-get install -y isc-dhcp-server

# Configure DHCP server
nano /etc/dhcp/dhcpd.conf

# Add the following configuration to the file:
# authoritative;
# subnet 192.168.1.0 netmask 255.255.255.0 {
#   range 192.168.1.100 192.168.1.200;
#   option routers 192.168.1.1;
#   option domain-name-servers 8.8.8.8, 8.8.4.4;
# }

# Restart DHCP service
systemctl restart isc-dhcp-server
