#!/bin/bash

# Install Postfix mail server
apt-get install -y postfix

# Configure Postfix
nano /etc/postfix/main.cf

# Customize the following settings:
# myhostname = your_domain.com
# mydestination = your_domain.com, localhost.localdomain, localhost

# Restart Postfix service
systemctl restart postfix
