#!/bin/bash

# Install vsftpd FTP server
apt-get install -y vsftpd

# Configure vsftpd
nano /etc/vsftpd.conf

# Uncomment and modify the following settings:
# anonymous_enable=NO
# local_enable=YES
# write_enable=YES

# Restart vsftpd service
systemctl restart vsftpd
